### ISSUE TITLE
got an unexpected keyword argument 'mimetype' in Django 1.7

### ISSUE THREAD

**Issue by kiatweitan** [django-de/django-simple-ratings#6]
rating/views.py line 38 need change to:

return HttpResponse('{"success": true}', content_type='application/json')

**Comment by zerok** [comment]
Thanks :) I will try to find some time to look into your issues :)

**Comment by zerok** [comment]
OK, looks like both are available in Django 1.4 so we should be able to change to content_type without breaking anything. Will create a PR once we have testing fixed (another PR on that will be created tomorrow). Thanks again :-)
